baseURL = "https://netlifywebsite1.github.io/"
languageCode = "en-us"
defaultContentLanguage = "en"
theme = "almeida-cv"
title = "resume stan wiggers"

[params]
colorDark = "#666"
colorLight = "#fff"
colorPageBackground = "#ddd"
colorPrimary = "#5bddeb"
colorPrimaryText = "#fff"
colorRightColumnBackground = "#f5f5f5"
colorSecondary = "#aaa"
pages = 1
