baseURL = "https://example.com/"
languageCode = "en-us"
defaultContentLanguage = "en"
theme = "almeida-cv"
title = "CV Stan Wiggers"

[params]
colorDark = "#666"
colorLight = "#fff"
colorPageBackground = "#ddd"
colorPrimary = "#5bddeb"
colorPrimaryText = "#fff"
colorRightColumnBackground = "#f5f5f5"
colorSecondary = "#aaa"
pages = 1
